name: "Build Docker Image For UAT: CMS"

on:
  push:
    branches:
      - deploy-web-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: web

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # - name: Build Website
      #   env:
      #     NODE_OPTIONS: "--max_old_space_size=4096"
      #   run: |
      #     corepack enable && corepack prepare pnpm@8.9.2 --activate
      #     pnpm i && pnpm nx run web:build
      #     echo "${{ env.RELEASE_VERSION }}" > services/web/dist/RELEASE.txt

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
