name: "Build Website"

on:
  push:
    branches:
      - deploy-web-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            libs
            services/web

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Build Website
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          # cd services/ && rm -rf $(ls -1 | grep -v '^web$') && cd ..
        run: |
          pnpm i && pnpm nx run web:build
          echo "${{ env.RELEASE_VERSION }}" > services/web/dist/RELEASE.txt

      # - name: Install Vercel CLI
      #   run: pnpm install --global vercel@latest

      # - name: Build Project Artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
